# -*- coding: utf-8 -*-
"""LA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g0cTHGXx5spsQkuIP0n-CnSuSo4TDs-F
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, r2_score


df = pd.read_csv('zcash_blocks.csv')


print("Dataset Head:")
print(df.head())
print("\nDataset Info:")
print(df.info())

df['timestamp'] = pd.to_datetime(df['timestamp'])


df['hour'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek


X = df[['block_size', 'hour', 'day_of_week']]
y = df['transaction_count']


X = X.fillna(0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


model_lr = LinearRegression()
model_lr.fit(X_train, y_train)
pred_lr = model_lr.predict(X_test)
score_lr = r2_score(y_test, pred_lr)


model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)
pred_rf = model_rf.predict(X_test)
score_rf = r2_score(y_test, pred_rf)


print(f"Linear Regression R2 Score: {score_lr:.4f}")
print(f"Random Forest R2 Score: {score_rf:.4f}")

if score_rf > score_lr:
    print("\nConclusion: The Random Forest model provided the best results.")
else:
    print("\nConclusion: The Linear Regression model provided the best results.")